// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.user_id", "fd934c5d-9442-402a-9f77-3d4504e1eaeb");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1575540792);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1575540912);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1575542918);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1575540552);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1575540432);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1575540672);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1575541152);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1575541032);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 768000);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1575539290);
user_pref("browser.laterrun.bookkeeping.sessionCount", 2);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 77);
user_pref("browser.newtabpage.activity-stream.impressionId", "{85e3bcec-4d37-4c5b-b791-416459fe39f1}");
user_pref("browser.newtabpage.activity-stream.migrationLastShownDate", 1575532800);
user_pref("browser.newtabpage.activity-stream.migrationRemainingDays", 3);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1575544052649");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1575545837649");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1575542914942");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1575546514942");
user_pref("browser.search.region", "IN");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20190215001400");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1575540412");
user_pref("browser.slowStartup.averageTime", 14365);
user_pref("browser.slowStartup.samples", 2);
user_pref("browser.startup.homepage_override.buildID", "20190215001400");
user_pref("browser.startup.homepage_override.mstone", "65.0.1");
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"toolbar-menubar\",\"TabsToolbar\",\"PersonalToolbar\"],\"currentVersion\":15,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.timesBeforeHidingSuggestionsHint", 0);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1575539321480");
user_pref("devtools.onboarding.telemetry.logged", true);
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "65.0.1");
user_pref("distribution.iniFile.exists.value", true);
user_pref("dom.push.userAgentID", "e6239e0e73414c3fa568de52967aff03");
user_pref("extensions.blocklist.lastModified", "Wed, 04 Dec 2019 18:51:07 GMT");
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.databaseSchema", 28);
user_pref("extensions.getAddons.cache.lastUpdate", 1575540794);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppBuildId", "20190215001400");
user_pref("extensions.lastAppVersion", "65.0.1");
user_pref("extensions.lastPlatformVersion", "65.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"c14b1ef7-45db-4098-a633-d8da275cca4c\",\"screenshots@mozilla.org\":\"6219220f-0aca-4d94-b0a7-a2bf95a2e5bb\",\"webcompat-reporter@mozilla.org\":\"88237bec-f518-41a6-8cd7-4ee1179654a7\",\"webcompat@mozilla.org\":\"ae9cf26c-da49-4c1b-a360-1d1598c24d3e\",\"baidu-code-update@mozillaonline.com\":\"5e0a2ff3-4dab-483b-ae8b-5c03aa56aa69\",\"fxmonitor@mozilla.org\":\"0040ef3b-7efc-4054-ab56-ca3e6b2afbcd\"}");
user_pref("idle.lastDailyNotification", 1575541723);
user_pref("lightweightThemes.usedThemes", "[]");
user_pref("media.gmp-manager.buildID", "20190215001400");
user_pref("media.gmp-manager.lastCheck", 1575539316);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1575541724);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "e5a6d4e9-3baf-4ac7-99e0-58513afb0b10");
user_pref("security.sandbox.plugin.tempDirSuffix", "7d664546-7c6a-4744-9f35-4a7066ab3950");
user_pref("services.blocklist.addons.checked", 1575540777);
user_pref("services.blocklist.gfx.checked", 1575540777);
user_pref("services.blocklist.onecrl.checked", 1575540777);
user_pref("services.blocklist.pinning.checked", 1575540777);
user_pref("services.blocklist.plugins.checked", 1575540777);
user_pref("services.settings.clock_skew_seconds", -105);
user_pref("services.settings.last_update_seconds", 1575540777);
user_pref("services.settings.main.language-dictionaries.last_check", 1575540777);
user_pref("services.settings.main.sites-classification.last_check", 1575540777);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1575541723);
user_pref("toolkit.startup.last_success", 1575540396);
user_pref("toolkit.telemetry.cachedClientID", "8b22a485-cdc9-411a-b107-9e56c0c1bddb");
user_pref("toolkit.telemetry.previousBuildID", "20190215001400");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
